### ISSUE TITLE
Error reading maps

### ISSUE THREAD

**Issue by kasturit** [aerospike/java-object-mapper#114]
When reading Maps where the the keys are references to Aerospike records and the values are Java objects, I get the following exception:

```
Exception in thread "main" java.lang.ClassCastException: class java.lang.Integer cannot be cast to class com.aerospike.mapper.tools.DeferredObjectLoader$DeferredObject (java.lang.Integer is in module java.base of loader 'bootstrap'; com.aerospike.mapper.tools.DeferredObjectLoader$DeferredObject is in unnamed module of loader 'app')
	at com.aerospike.mapper.tools.mappers.MapMapper.fromAerospikeFormat(MapMapper.java:80)
	at com.aerospike.mapper.tools.ClassCacheEntry.constructAndHydrate(ClassCacheEntry.java:949)
	at com.aerospike.mapper.tools.ClassCacheEntry.constructAndHydrate(ClassCacheEntry.java:924)
	at com.aerospike.mapper.tools.converters.MappingConverter.convertToObject(MappingConverter.java:110)
	at com.aerospike.mapper.tools.AeroMapper.read(AeroMapper.java:347)
	at com.aerospike.mapper.tools.AeroMapper.read(AeroMapper.java:281)
	at com.aerospike.mapper.tools.AeroMapper.read(AeroMapper.java:273)
	at TestMapper.main(TestMapper.java:32)
```

Simple test code demonstrating this error is found here: https://github.com/kasturit/aerospike-test

Note that writing to Aerospike works fine, and the Maps are stored as expected, with the record key as the key, and the serialized Java object (or primitive) as the value.  Reading the data back is the problem.

**Comment by roimenashe** [comment]
@kasturit 
Don't use `B` as the key type in `bIntegerMap`, use `Integer` (`b.id`'s type) which is what you actually want to store as a key - Integer.

After changing your code to:
`A` Object Model:
```java
@AerospikeRecord(namespace = "test", set = "a")
public class A {

    @AerospikeKey
    public int id;

    @AerospikeReference
    public Map<Integer, Integer> bIntegerMap = new HashMap<>();
}
```

And `line 19` of `TestMapper.main()`
from:
```java
a.bIntegerMap.put(b, 4);
```

to:
```java
a.bIntegerMap.put(b.id, 4);
```

Test is passing and you can successfully read the object.

**Comment by roimenashe** [comment]
Closing.
